name: Build NumPy 1.18.5 Wheels for Python 3.10.14

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.14"]
        platform: [
          "manylinux_2_17_x86_64", 
          "manylinux_2_28_x86_64", 
          "linux_x86_64"
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools numpy-build-system

    - name: Build wheel
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
        PLATFORM: ${{ matrix.platform }}
      run: |
        pip wheel numpy==1.18.5 \
          --only-binary=:all: \
          --python-version $PYTHON_VERSION \
          --platform $PLATFORM \
          -w ./dist

    - name: Upload wheel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: numpy-wheels-${{ matrix.python-version }}-${{ matrix.platform }}
        path: ./dist/*.whl
        retention-days: 7

    - name: Verify wheel
      run: |
        pip install ./dist/*.whl
        python -c "import numpy; print(numpy.__version__)"
